data:
  lr: 0.0001
  train:
    adjacency_matrix_path: ./train/adj_matrix.npy
    dataset_path: ./train/dynamics.npz
  test:
    adjacency_matrix_path: ./test/adj_matrix.npy
    dataset_path: ./test/dynamics.npz
  data_keys:
  - train
  - test
  Dynamics:
    dataset_path: ../Data/Dynamics/train_data.pkl
  A_C:
    adjacency_matrix_path: ../Data/TimeSeries/Dynamics/A_C/adj_matrix.npy
    dataset_path: ../Data/TimeSeries/Dynamics/A_C/dynamics.npz
    node_num: 300
    speed_mean: 0.014326641690492387
    speed_std: 0.7911929065346424
    time_step: 500
model:
  edge_feature_dim: 4
  hidden_dim: 16
  loss_lambda: 1.5
  message_dim: 2
  meta_dim: 16
  meta_lr: 0.0001
  node_feature_dim: 2
  output_dim: 2
  sp: true
  tp: true
  update_lr: 0.0005
  update_step: 5
  update_step_test: 10
task:
  batch_size: 4
  his_num: 12
  pred_num: 6
  task_num: 2
  test_batch_size: 8
